default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_development
  username: airbnb
  password: root
  host: localhost

test:
  <<: *default
  database: airbnb_test
  username: airbnb
  password: root
  host: localhost

production:
  <<: *default
  database: airbnb_production
  username: airbnb
  password: <%= ENV["AIRBNB_DATABASE_PASSWORD"] %>
  host: localhost
